# The beehive example configuration

# The node name in the cluster
name = "node4"

# The RPC address to serve requests
raftAddr = "node4:10001"

# The RPC address to serve requests
rpcAddr = "node4:10002"

[prophet]
# The application and prophet RPC address, send heartbeats, alloc id, watch event, etc. required
rpcAddr = "node4:9527"

# Store cluster metedata
storeMetadata = false

# The clusters client address list, required while storeMetadata is false
clusters = [
    "node1:2371",
    "node2:2371",
    "node3:2371"
]

[metric]
# The prometheus pushgateway address
addr = "pushgateway:9091"

# The interval seconds to push the metrics to prometheus pushgateway
interval = 10

# The prometheus job
job = "busybee"

instance = "node4"