# The beehive example configuration

# The node name in the cluster
name = "node3"

# The RPC address to serve requests
raftAddr = "node3:10001"

# The RPC address to serve requests
rpcAddr = "node3:10002"

[prophet]
# The application and prophet RPC address, send heartbeats, alloc id, watch event, etc. required
rpcAddr = "node3:9527"

# Store cluster metedata
storeMetadata = true

# The embed etcd client address, required while storeMetadata is true
clientAddr = "node3:2371"

# The embed etcd peer address, required while storeMetadata is true
peerAddr = "node3:2381"

# The cluster seed node, to join the cluster, required while storeMetadata is true
seed = "node1:2371"

# The maximum count of transfer replica leader operator.
maxRebalanceLeader = 4

# The maximum count of remove|add replica operator.
maxRebalanceReplica = 2

# The maximum count of replica kind operator.
maxScheduleReplica = 8

[metric]
# The prometheus pushgateway address
addr = "pushgateway:9091"

# The interval seconds to push the metrics to prometheus pushgateway
interval = 10

# The prometheus job
job = "busybee"

instance = "node3"