version: '2.1'
services:
  pushgateway:
    image: prom/pushgateway:v1.1.0
    expose:
      - 9091
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:v2.9.2
    depends_on:
      - pushgateway
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:5.4.3
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    expose:
      - 3000
    ports:
      - "3000:3000"

  node1:
    image: deepfabric/busybee
    ports:
      - "8081:8080"
    volumes:
      - ./cfg/node1.toml:/etc/node.toml
    command: 
      - --addr=node1:8080
      - --data=/tmp
      - --beehive-cfg=/etc/node.toml

  node2:
    image: deepfabric/busybee
    ports:
      - "8082:8080"
    volumes:
      - ./cfg/node2.toml:/etc/node.toml
    command: 
      - --addr=node2:8080
      - --data=/tmp
      - --beehive-cfg=/etc/node.toml

  node3:
    image: deepfabric/busybee
    ports:
      - "8083:8080"
    volumes:
      - ./cfg/node3.toml:/etc/node.toml
    command: 
      - --wait=10
      - --addr=node3:8080
      - --data=/tmp
      - --beehive-cfg=/etc/node.toml

  node4:
    image: deepfabric/busybee
    ports:
      - "8084:8080"
    volumes:
      - ./cfg/node4.toml:/etc/node.toml
    command: 
      - --wait=10
      - --addr=node4:8080
      - --data=/tmp
      - --beehive-cfg=/etc/node.toml